django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('allauth.urls')),
    path("profiles/", include("profiles.urls", namespace="profiles")),
    path("posts/", include("posts.urls", namespace="posts"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path("",views.home,name="home")
]

posts/urls.py
from django.urls import path
from .views import posts_comment_and_list_view, like_dislike_post, PostDelete, PostUpdate

app_name = "posts"
urlpatterns = [
    path("", posts_comment_and_list_view, name="post"),
    path("like/", like_dislike_post, name="like"),
    path("<pk>/delete", PostDelete.as_view(), name="post-delete"),
    path("<pk>/update", PostUpdate.as_view(), name="post-update")
]

profiles/urls.py
from django.urls import path
from .views import (
    profile, 
    invite_receive, 
    profiles_list,
    send_invitation, 
    invite_profiles_list,
    remove_from_friends,
    accept_invitation,
    reject_invitation,
    ProfilesList,
    ProfilesDetail
    )

app_name = "profiles"
urlpatterns = [
    path("", ProfilesList.as_view(), name="all-profiles"),
    path("my-profile/", profile, name="my-profile"),
    path("invites/", invite_receive, name="invites"),
    path("invites-list/", invite_profiles_list, name="invite-list"),
    path("send-invitation/", send_invitation, name="send-invite"),
    path("remove-friend/", remove_from_friends, name="remove-friend"),
    path("<slug>/", ProfilesDetail.as_view(), name="profiles-detail"),
    path("invites/accept/", accept_invitation, name="accept-invite"),
    path("invites/reject/", reject_invitation, name="reject-invite"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    user = request.user
    context={"user":user}

    return render(request, "home/home.html", context)

home/templates/home/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock title %}

{% block content %}
{{user}}  
{% endblock content %}

{% block scripts %}
{% endblock scripts %}

home/templates/home/navbar.html
{% url "home:home" as path_to_home %}
{% url "posts:post" as path_to_posts %}
{% url "profiles:my-profile" as path_to_my_profile %}
{% url "profiles:invites" as path_to_invites %}
{% url "profiles:invite-list" as path_to_invite_list %}
{% url "profiles:all-profiles" as path_to_all_profiles %}

<div class="ui inverted menu navbar mb-7">
    <div class="ui container">
      <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
          <h3>bffbook</h3>
      </a>
      {% if request.user.is_authenticated %}
      <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
          Posts
      </a>
      {% endif %}
  
      <div class="right menu">
          {% if request.user.is_authenticated %}
          <div class="item">
              <div class="ui floating dropdown icon button teal"> Friends
                  <i class="dropdown icon"></i>
                  <div class="menu">
                      <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                          All Profiles
                      </a>
                      <a href="{{path_to_invite_list}}" class="{% if request.path == path_to_invite_list %}active{% endif %} item">
                          Send Invites
                      </a>
                      <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item">
                          Received Invites &nbsp; <div class="ui blue horizontal label">{{invites_number}}</div>
                      </a>
                  </div>
               </div>
          </div>
               <div class="item">
                <form action="" method="GET">
                  <div class="ui action left icon input">
                  <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                  <i class="search icon"></i>
                  <button type='submit' class="ui button">Search</button>
                  </div>
              </form>
              </div>
          
              <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                  <img src={{avatar.url}} class="ui avatar image" alt="avatar">&nbsp;
                   {{ request.user }}
              </a>
  
              <a href="" class="ui item">
                  Logout
              </a>
          {% else %}
          <a href="" class="ui item">
                  Login
              </a>
          {% endif %}
      </div>
    </div>
  </div>