django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('allauth.urls')),
    path("profiles/", include("profiles.urls", namespace="profiles")),
    path("posts/", include("posts.urls", namespace="posts"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path("",views.home,name="home")
]

profiles/urls.py
from django.urls import path
from .views import (
    profile, 
    invite_receive, 
    profiles_list,
    send_invitation, 
    invite_profiles_list,
    remove_from_friends,
    accept_invitation,
    reject_invitation,
    ProfilesList,
    ProfilesDetail
    )

app_name = "profiles"
urlpatterns = [
    path("", ProfilesList.as_view(), name="all-profiles"),
    path("my-profile/", profile, name="my-profile"),
    path("invites/", invite_receive, name="invites"),
    path("invites-list/", invite_profiles_list, name="invite-list"),
    path("send-invitation/", send_invitation, name="send-invite"),
    path("remove-friend/", remove_from_friends, name="remove-friend"),
    path("<slug>/", ProfilesDetail.as_view(), name="profiles-detail"),
    path("invites/accept/", accept_invitation, name="accept-invite"),
    path("invites/reject/", reject_invitation, name="reject-invite"),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q
from django.shortcuts import reverse

class ProfileManager(models.Manager):
    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        queryset = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        print(queryset)

        accepted = []
        for relation in queryset:
            if relation.status == "accepted":
                accepted.append(relation.receiver)
                accepted.append(relation.sender)
        print(accepted)
        available = [profile for profile in profiles if profile not in accepted]
        print(available)
        return available

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles

class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="no bio..", max_length=300)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    avatar = models.ImageField(default="avatar.png", upload_to="avatars/")
    friends = models.ManyToManyField(User, blank=True, related_name="frinends")
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

    def get_absolute_url(self):
        return reverse("profiles:profiles-detail", kwargs={"slug": self.slug})
        
    def get_friends(self):
        return self.friends.all()
    
    def get_friends_number(self):
        return self.friends.all().count()
    
    def get_posts_number(self):
        return self.posts.all().count()
    
    def get_all_authors_posts(self):
        return self.posts.all
    
    def get_likes(self):
        likes = self.like_set.all()
        total_likes = 0

        for like in likes:
            if like.value=="Like":
                total_likes += 1
        return total_likes
    
    def get_likes_recieved_number(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.likes.all().count()
        return total_liked

    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug=="":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)

STATUS_CHOICES = (
    ("send", "send"),
    ("accepted", "accepted")
)

class RelationshipManager(models.Manager):
    def invitations_receive(self, receiver):
        queryset = Relationship.objects.filter(receiver=receiver, status="send")
        return queryset

class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="sender")   
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="receiver")   
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now_add=True)
    created = models.DateTimeField(auto_now_add=True)
    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

profiles/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("first_name", "last_name", "bio", "email", "avatar")

profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile, Relationship
from .forms import ProfileForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

@login_required
def profile(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False

    if request.method == "POST":
        form.save()
        confirm = True

    context = {
        "profile":profile, 
        "form":form,
        "confirm":confirm,
    }
    
    return render(request, "profiles/profile.html", context)

@login_required
def invite_receive(request):
    profile = Profile.objects.get(user=request.user)
    queryset = Relationship.objects.invitations_receive(profile)
    results = list(map(lambda x: x.sender, queryset))
    is_empty = False

    if len(results) == 0:
        is_empty = True

    context = {
                "queryset":results, 
                "is_empty":is_empty
              }
    
    return render(request, "profiles/invites.html", context)

@login_required
def invite_profiles_list(request):
    user = request.user    
    queryset = Profile.objects.get_all_profiles(user)

    context = {"queryset":queryset}

    return render(request, "profiles/invite-list.html", context)

@login_required
def profiles_list(request):
    user = request.user    
    queryset = Profile.objects.get_all_profiles(user)

    context = {"queryset":queryset}

    return render(request, "profiles/profiles-list.html", context)

@login_required
def send_invitation(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
        relation = Relationship.objects.create(sender=sender, receiver=receiver, status="send")

        return redirect(request.META.get("HTTP_REFERER"))

    return redirect("profiles:my-profile")

@login_required
def remove_from_friends(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
        relation = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender))
        )

        relation.delete()

        return redirect(request.META.get("HTTP_REFERER"))

    return redirect("profiles:my-profile")

@login_required
def accept_invitation(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        relationship = get_object_or_404(Relationship, sender=sender, receiver=receiver)

        if relationship.status == "send":
            relationship.status = "accepted"
            relationship.save()

    return redirect("profiles:invites")

@login_required
def reject_invitation(request):
    if request.method == "POST":
        pk = request.POST.get("profile_pk")
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        relationship = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        relationship.delete()
    return redirect("profiles:invites")

class ProfilesDetail(LoginRequiredMixin, DetailView):
    model = profile
    template_name = "profiles/profiles-detail.html"

    def get_object(self, slug=None):
        slug = self.kwargs.get("slug")
        profile = Profile.objects.get(slug=slug)

        return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        relationship_reciever = Relationship.objects.filter(sender=profile)
        relationship_sender = Relationship.objects.filter(receiver=profile)
        receivers = []
        senders = []

        for item in relationship_reciever:
            receivers.append(item.receiver.user)
            
        for item in relationship_sender:
            senders.append(item.sender.user)

        context["receivers"] = receivers
        context["senders"] = senders
        context['posts'] = self.get_object().get_all_authors_posts()
        # contxt['len_posts'] = True if len(self.get_object().get_all_authors_posts()) > 0 else False

        return context

class ProfilesList(LoginRequiredMixin, ListView):
    model = Profile
    template_name = "profiles/profiles-list.html"

    def get_queryset(self):
        queryset = Profile.objects.get_all_profiles(self.request.user)        
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        relationship_reciever = Relationship.objects.filter(sender=profile)
        relationship_sender = Relationship.objects.filter(receiver=profile)
        receivers = []
        senders = []

        for item in relationship_reciever:
            receivers.append(item.receiver.user)
            
        for item in relationship_sender:
            senders.append(item.sender.user)

        context["receivers"] = receivers
        context["senders"] = senders
        context["is_empty"] = False

        if len(self.get_queryset()) == 0:
            context["is_empty"] = True

        return context

profiles/templates/profiles/invite-list.html
{% extends 'base.html' %}

{% block title %}
invite friends
{% endblock title %}

{% block content %}
    <ul>
        {% for item in queryset %}
            <li>{{item}}</li>
        {% endfor %}
    </ul>
{% endblock content %}

profiles/templates/profiles/invites.html
{% extends "base.html" %}

{% block title %}
    my invites
{% endblock title %}

{% block content %}
    
    {% if is_empty %}
        <h3>No invites</h3>
    {% endif %}
    {% for obj in queryset %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img src="{{obj.avatar.url}}" class="ui small circular image" alt="">
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href="">
                            <button class="ui primary button w-big mb-5">See profile</button>
                        </a>
                        <form action="{% url 'profiles:accept-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui positive basic button w-big mb-5 mt-7">
                                <i class="check icon"></i>
                                Accept invite
                            </button>
                        </form>
                        <form action="{% url 'profiles:reject-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button w-big mb-5 mt-7">
                                <i class="close icon"></i>
                                Reject invite
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock content %}

profiles/templates/profiles/profile.html
{% extends "base.html" %}

{% block title %}
my profile
{% endblock title %}

{% block content %}

<div class="ui modal mymodal">
    <i class="close icon"></i>
    <div class="header">
        Update your Profile
    </div>
    <div class="image content">
      <div class="ui medium image">
        <img src="{{profile.avatar.url}}">
      </div>
      <div class="description">
        <div class="ui header">We've auto-chosen a profile image for you.</div>
        <form method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
        
      </div>
    </div>
    <div class="actions">
      <button type="submit" class="ui positive right labeled icon button">
            Update
        <i class="checkmark icon"></i>
      </button>
    </form>
    </div>
  </div>



<div class="ui segment">
    {% if confirm %}
        <div class="ui green message">Your profile has been updated</div>
    {% endif %}
    <h3>my profile: {{request.user}}</h3>
    <div class="ui grid">
    <div class="row">
        <div class="six wide column">
            <img src={{profile.avatar.url}} class="ui secondary button" alt="">
            <div class="row mt-5">            
                <button id="modal-btn" class="ui secondary button">Update your Profile</button>
            </div>
        </div>
    </div>
    <div class="ten wide column">
        <table class="ui table">
            <tbody>
                <tr>
                    <td>username</td>
                    <td>{{profile.user}}</td>
                </tr>
                <tr>
                    <td>first name</td>
                    <td>{{profile.first_name}}</td>
                </tr>
                <tr>
                    <td>last name</td>
                    <td>{{profile.last_name}}</td>
                </tr>
                <tr>
                    <td>bio</td>
                    <td>{{profile.bio}}</td>
                </tr>
                <tr>
                    <td>email</td>
                    <td>{{profile.email}}</td>
                </tr>
                <tr>
                    <td>number of friends</td>
                    <td>{{profile.get_friends_number}}</td>
                </tr>
                <tr>
                    <td>friends</td>
                    <td>
                        <ul>
                            {% for friend in profile.get_friends %}
                                <li>{{friend}}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>posts number</td>
                    <td>{{profile.get_posts_number}}</td>
                </tr>
                <tr>
                    <td>likes number</td>
                    <td>{{profile.get_likes}}</td>
                </tr>
            </tbody>
        </table>
    </div>
    </div>
</div>

{% endblock content %}

profiles/templates/profiles/profiles-detail.html
{% extends 'base.html' %}

{% block title %}
profile detail
{% endblock title %}

{% block content %}
<div class="ui grid">
    <br>
    <div class="row">
        <div class="four wide column">
            <img class="ui medium rounded image" src={{object.avatar.url}}>
            <h1>{{object.user}}</h1>
            <div class="ui vertical fluid menu">
                <div class="item">
                    Posts
                    <div class="ui label">{{ object.get_posts_number }}</div>
                </div>
                <div class="item">
                    Likes given
                    <div class="ui label">{{ object.get_likes_given_number }}</div>
                </div>
                <div class="item">
                    Likes received
                    <div class="ui label">{{ object.get_likes_recieved_number }}</div>
                </div>
                <div class="item">
                    Friends
                    <div class="ui label">{{ object.get_friends_number }}</div>
                </div>
            </div>

            {% if object.user not in rel_receiver and object.user not in rel_sender %}
                <form action="{% url 'profiles:send-invite' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                </form>
            {% endif %}

            {% if object.user in rel_receiver and request.user not in object.friends.all %}
                <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
            {% endif %}

            {% if request.user in object.friends.all %}
                <form action="{% url 'profiles:remove-friend' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                </form>
            {% endif %}

        </div>
        <div class="twelve wide column">
                {% for post in posts %}
                    <div class="segment ui fluid">
                        {{post.content}}
                    </div>
                {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

profiles/templates/profiles/profiles-list.html
{% extends "base.html" %}

{% block title %}
all profiles
{% endblock title %}

{% block content %}

    {% if is_empty %}
        <h1>No profiles to interact with</h1>
        
    {% endif %}        

    {% for obj in object_list %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img src={{obj.avatar.url}} alt="" class="ui small circular image">
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.email}}</p>
                        <p>{{obj.bio}}</p>
                        <a href={{obj.get_absolute_url}}>
                            <button class="ui primary button mb-7 w-big mt-5">See Profile</button>
                        </a>
                        {% if obj.user not in receivers and obj.user not in senders %}
                            <form action="{% url 'profiles:send-invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <button type="submit" class="ui positive basic button mb-7 w-big mt-5"><i class="plus square icon"></i>Add to friends</button>
                            </form>
                         {% endif %}

                        {% if obj.user in receivers and request.user not in obj.friends.all %}
                            <button class="ui disabeled button mb-7 w-big mt-5"><i class="user icon"></i>waiting for a approval</button>
                        {% endif %}
                        
                        {% if request.user in obj.friends.all %}
                        <form action="{% url 'profiles:remove-friend' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button mb-7 w-big mt-5"><i class="minus square icon"></i>Remove from Friends</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock content %}