django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('allauth.urls')),
    path("profiles/", include("profiles.urls", namespace="profiles")),
    path("posts/", include("posts.urls", namespace="posts"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path("",views.home,name="home")
]

posts/urls.py
from django.urls import path
from .views import posts_comment_and_list_view, like_dislike_post, PostDelete, PostUpdate

app_name = "posts"
urlpatterns = [
    path("", posts_comment_and_list_view, name="post"),
    path("like/", like_dislike_post, name="like"),
    path("<pk>/delete", PostDelete.as_view(), name="post-delete"),
    path("<pk>/update", PostUpdate.as_view(), name="post-update")
]

posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile

class Post(models.Model):
    content = models.TextField()
    image = models.ImageField(upload_to="posts", validators=[FileExtensionValidator(["png", "jpg", "jpeg"])],  blank=True)
    likes = models.ManyToManyField(Profile, blank=True, related_name="likes")
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="posts")

    def __str__(self):
        return str(self.content[:20])
    def number_likes(self):
        return self.likes.all().count()
    def number_comments(self):
        return self.comment_set.all().count()
    
    class Meta:
        ordering = ("-created",)

class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)

LIKE_CHOICES = (
    ("Like", "Like"),
    ("Dislike", "Dislike")
)

class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={"rows":2}))
    class Meta:
        model = Post
        fields = ("content", "image")

class CommentForm(forms.ModelForm):
    body = forms.CharField(label="", widget=forms.TextInput(attrs={"placeholder":"Your Comment!"}))
    class Meta:
        model = Comment
        fields = ("body",)

posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Like
from django.urls import reverse_lazy
from .forms import PostForm, CommentForm
from profiles.models import Profile
from django.views.generic import UpdateView, DeleteView
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

@login_required
def posts_comment_and_list_view(request):
    queryset = Post.objects.all()
    profile = Profile.objects.get(user=request.user)

    # intials
    post_form = PostForm()
    comment_form = CommentForm()
    post_add = False

    profile = Profile.objects.get(user=request.user)

    if "submit_post_form" in request.POST:
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            instance = post_form.save(commit=False)
            instance.author = profile
            instance.save()
            profile_form = PostForm()
            post_add = True

    if "submit_comment_form" in request.POST:
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get("post_id"))
            instance.save()
            comment_form = CommentForm()

    context = {
        "queryset":queryset,
        "profile":profile,
        "post_form":post_form,
        "comment_form":comment_form,
        "post_add":post_add
    }

    return render(request, "posts/posts.html", context)

@login_required
def like_dislike_post(request):
    user = request.user
    if request.method == "POST":
        post_id = request.POST.get("post_id")
        post_obj = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)

        if profile in post_obj.likes.all():
            post_obj.likes.remove(profile)
        else:
            post_obj.likes.add(profile)
        
        like, created = Like.objects.get_or_create(user=profile, post_id=post_id)

        if not created:
            if like.value == "Like":
                like.value = "Dislike"
            else:
                like.value = "Like"
        else:
            like.value

            post_obj.save()
            like.save()
        
    data = {
        "value": like.value,
        "counter": post_obj.likes.all().count()
    }
    
    return JsonResponse(data, safe=False)

    return redirect("posts:post")

class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = "posts/post-delete.html"
    success_url = reverse_lazy("posts:post")

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get("pk")
        obj = Post.objects.get(pk=pk)
        if not obj.author.user == self.request.user:
            messages.warning(self.request, "You need to be the author to delete this post")
        return obj

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "posts/post-update.html"
    success_url = reverse_lazy("posts:post")

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None, "You need to be the author to update this post")
            return super().form_invalid(form)

posts/templates/posts/post-delete.html
{% extends "base.html" %}

{% block title %}
post delete
{% endblock title %}

{% block content %} 

    
    {% if message %}
        {% for message in messages %}
            {% if "warning" in messages.tags %}
                <div class="ui negative message">
                    <div class="header">
                        {{message}}
                    </div>
                </div>
            {% endif %}
        {% endfor %}    
    {% endif %}

    {% if not messages %}
        <div class="ui segment">
            <h3 style="color: red;">Delete post!</h3>
            <form method="POST">
                {% csrf_token %}
                <p>r u sure u want delete this post?</p>
                <button type="submit">Delete</button>
            </form>
        </div> 
    {% endif %}

{% endblock content %}

posts/templates/posts/post-update.html
{% extends "base.html" %}

{% block title %}
    post update
{% endblock title %}

{% block content %}
    <div class="ui segment">
            <h3>Update Post</h3>
            <form action="" method="POST" class="ui form" enctype="multipart/form-data">
                {% csrf_token %}
                {{form}}
                <button type="submit" class="ui button primary mt-5">Update</button>
            </form>
    </div>
{% endblock content %}

posts/templates/posts/posts.html
{% extends 'base.html' %}

{% block title %}main page{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="eleven wide column">
        {% for obj in queryset %}

        <div class="ui fluid card">
            <div class="content">
                <div class="right floated meta">
                <div class="ui grid">
                    <div class="row">
                        {% ifequal request.user obj.author.user %}
                            <a href="{% url 'posts:post-update' obj.pk %}"><button class="ui button bwhite-lg ">Update</button></a>
                            <a href="{% url 'posts:post-delete' obj.pk %}"><button class="ui button bwhite-lg ">Delete</button></a>
                        {% endifequal %}
                    </div>
                </div>
                    
                </div>
                <img class="ui avatar image" src={{obj.author.avatar.url}}> 
                {{ obj.author.user }} - {{ obj.created|timesince}} ago
            </div>
            <div class="ui fluid image">
                {% if obj.image %}
                    <img src={{obj.image.url}}>
                {% endif %}
            </div>
            <div class="content">
                <p> {{ obj.content }} </p>
                <div class="right floated">
                    <form action="{% url 'posts:like' %}" method="POST" class="like-form" id="{{obj.id}}">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{obj.id}}>
                            <button type="submit" class="ui button like-btn{{obj.id}}">
                                {% if profile not in obj.likes.all %}
                                    like
                                {% else %}
                                    Dislike
                                {% endif %}
                            </button>
                            <div class="ui grid">
                                <div class="column">
                                    <div class="likes-count{{obj.id}}">{{obj.number_likes}}</div>
                                </div>
                                <div class="column">
                                    likes
                                </div>
                            </div>
                    </form>
                </div>
                <i class="comment icon"></i>
                <span> {{ obj.number_comments }} comments</span>
            </div>
            <div class="extra content">
                <div class="mb-5">
                  
                </div>
                <button class="cmt_btn ui button mb-5">show / hide comments</button>
                <div class="comment-box">
                {% if obj.comment_set.all %}
                    {% for comment in obj.comment_set.all %}
                    
                        <div class="ui segment mb-5">
                            <img class="ui avatar image" src={{comment.user.avatar.url}}>
                            <span>{{ comment.user }}</span>
                            <div class='mt-5'>{{ comment.body }}</div>
                        </div>
                    
                    {% endfor %}
                {% endif %}
                </div>
  
                <form action="" method="POST"class='ui fluid form'>
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value={{obj.id}}>
                    {{ comment_form }}
                    <button type="submit" name="submit_comment_form" class="ui primary button mt-5 w-full">Send</button>
                </form>
            </div>
        </div>


        {% endfor %}
    </div>
    <div class="five wide column">
        <div class="ui segment">
            {% if post_add %}
                <div class="ui green message">Post added</div>
            {% endif %}
            <form action="" method="POST" class='ui form' enctype="multipart/form-data">
                {% csrf_token %}
                {{post_form}}
                <button type='submit' name="submit_post_form" class="ui positive button w-full mt-5">Post</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %} 
    <script>
        $( document ).ready(function() {
            let display = false
            $(".cmt_btn").click(function () {
                if (display===false) {
                    $(this).next(".comment-box").show("slow");
                    display=true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }  
            });

            $(".like-form").submit(function(e){
                e.preventDefault()
                const post_id = $(this).attr("id")
                const like = $(`.like-btn${post_id}`).text()
                const trim = $.trim(like)
                const url = $(this).attr("action")
                
                let res;
                const likes = $(`.likes-count${post_id}`). text()
                const trimCount = parseInt(likes)
            
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                        'post_id':post_id,
                    },
                    success: function(response) {
                        if(trim === 'Unlike') {
                            $(`.like-btn${post_id}`).text('Like')
                            res = trimCount - 1
                        } else {
                            $(`.like-btn${post_id}`).text('Unlike')
                            res = trimCount + 1
                        }

                        $(`.likes-count${post_id}`).text(res)
                    },
                    error: function(response) {
                        console.log('error', response)
                    }
                }) 

            })

        });
    </script>
{% endblock scripts %}